/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Heapp */

#ifndef _Included_Heapp
#define _Included_Heapp
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Heapp
 * Method:    HeapWork
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_Heapp_HeapWork
  (JNIEnv *, jobject, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
