/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bsu.fpmi.educational_practice2019;

import javax.swing.JOptionPane;


enum ButtonValues 
{
    button, button1, button2
}

enum LabelValues 
{
    label, label1, label2
}
public class myComponent extends javax.swing.JPanel {

    /**
     * Creates new form myComponent
     */
    public myComponent()
    {
        this.setFocusable(true);
        initComponents();   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("press button");

        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(108, 108, 108)
                .addComponent(jButton1)
                .addContainerGap(110, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(53, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(32, 32, 32)
                .addComponent(jButton1)
                .addGap(31, 31, 31))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       jButton1.setFocusable(false);
        JOptionPane.showMessageDialog(jButton1, "Button pressed");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        if (Character.isLetterOrDigit(evt.getKeyChar()))
            JOptionPane.showMessageDialog(jButton1, "Entered symbol: "+evt.getKeyChar());
    }//GEN-LAST:event_formKeyPressed

   
     
    
     LabelValues labels;

    public void setjLabel(LabelValues labels) {
        this.labels = labels;
        switch (labels) 
        {
            case label:
                jLabel1.setText("Press button");
                break;
            case label1:
                jLabel1.setText("Enter symbol");
                break;
            case label2:
                jLabel1.setText("Press button and enter symbol");
                break;

        }
    }

    public LabelValues getjLabel() {
        return labels;
    }

    ButtonValues buttons;

    public void setjButton(ButtonValues buttons) {
        this.buttons = buttons;
        switch (buttons) {
            case button:
                jButton1.setText("OK");
                break;
            case button1:
                jButton1.setText("push");
                break;
            case button2:
                jButton1.setText("accept");
                break;
        }
    }

    public ButtonValues getjButton() {
        return buttons;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
